// Alan's United Auto - collated text list importer
// All pasted quotation items are imported into ONE repair section. Manual segmentation can be done afterwards.
(function(){
  const NO_QTY_CONTEXT=/labou?r|workmanship|diagnos|inspection fee|outside service|program|coding|calibrat|road test|service charge/i;
  function escHtml(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
  function cleanLine(s){return String(s||'').replace(/[•·]/g,' ').replace(/\t/g,' ').replace(/\s+/g,' ').trim()}
  function extractTopFields(lines){const fields={},patterns={customer:/^(?:customer(?:\s*name)?|name)\s*[:\-]\s*(.+)$/i,phone:/^(?:phone|mobile|contact|tel)\s*[:\-]\s*(.+)$/i,vehicle:/^(?:vehicle(?:\s*(?:no|number))?|car\s*(?:no|number)|registration|reg\s*no)\s*[:\-]\s*(.+)$/i,model:/^(?:model|vehicle\s*model|car\s*model)\s*[:\-]\s*(.+)$/i,mileage:/^(?:mileage|odo|odometer)\s*[:\-]\s*(.+)$/i};const consumed=new Set();lines.forEach((line,i)=>{for(const[k,rx]of Object.entries(patterns)){const m=line.match(rx);if(m){fields[k]=m[1].trim();consumed.add(i);break}}});return{fields,consumed}}
  function parseQtyAndDesc(body){let q='1 pc',desc=body.trim(),m;const unitRx='pcs?|pc|sets?|set|bottles?|bottle|litres?|liters?|ltr|l|units?|unit|pairs?|pair|boxes?|box|packs?|pack|tins?|tin|cans?|can';const fmtUnit=(n,u)=>{u=String(u||'').toLowerCase();if(/^l(?:tr)?$|^lit/.test(u))return `${n} L`;if(/^pc/.test(u))return `${n} pcs`;if(/^set/.test(u))return `${n} set`;if(/^bottle/.test(u))return `${n} bottle`;if(/^unit/.test(u))return `${n} unit`;if(/^pair/.test(u))return `${n} pair`;if(/^box/.test(u))return `${n} box`;if(/^pack/.test(u))return `${n} pack`;if(/^tin/.test(u))return `${n} tin`;if(/^can/.test(u))return `${n} can`;return `${n} ${u}`};function strip(match){desc=(desc.slice(0,match.index)+' '+desc.slice(match.index+match[0].length)).replace(/\s+/g,' ').trim()}m=desc.match(/(?:^|\s|[,;()\-])x\s*([0-9]+(?:\.\d+)?)(?=\s|$|[,;()\-])/i);if(m){q=`${m[1]} pcs`;strip(m);return{q,desc}}m=desc.match(/(?:^|\s|[,;()\-])([0-9]+(?:\.\d+)?)\s*x(?=\s|$|[,;()\-])/i);if(m){q=`${m[1]} pcs`;strip(m);return{q,desc}}m=desc.match(new RegExp('(?:^|\\s|[,;()\\-])([0-9]+(?:\\.\\d+)?)\\s*('+unitRx+')(?=\\s|$|[,;()\\-])','i'));if(m){q=fmtUnit(m[1],m[2]);strip(m);return{q,desc}}const nums=[...desc.matchAll(/(?:^|\s)([1-9]|1[0-9]|20)(?=\s|$)/g)];if(nums.length===1){m=nums[0];const around=desc.toUpperCase();if(!/\b(?:5W\d{2}|0W\d{2}|10W\d{2}|12V|24V|48V|AH|MM|CM|INCH|R\d{2}|DOT\s*\d|SAE|API|MB\s*\d|BMW\s*LL|VW\s*\d)\b/i.test(around)){q=`${m[1]} pcs`;strip(m);return{q,desc}}}return{q,desc}}
  function findLikelyPrice(raw){const explicit=[...raw.matchAll(/(?:@\s*|S\$\s*|SGD\s*|\$\s*)([0-9][0-9,]*(?:\.\d{1,2})?)/ig)];if(explicit.length){const m=explicit[explicit.length-1],n=Number(m[1].replace(/,/g,''));return Number.isFinite(n)?{n,start:m.index,end:m.index+m[0].length}:null}const beforeQty=[...raw.matchAll(/(?:^|\s|[-–—:=])([0-9][0-9,]*(?:\.\d{1,2})?)\s*(?=x\s*[0-9]+\b)/ig)];if(beforeQty.length){const m=beforeQty[beforeQty.length-1],token=m[1],n=Number(token.replace(/,/g,''));if(Number.isFinite(n)&&n>=5&&!(n>=1900&&n<=2100)){const rel=m[0].lastIndexOf(token),start=m.index+rel;return{n,start,end:start+token.length}}}const candidates=[],rx=/(^|\s|[-–—:=])([0-9][0-9,]*(?:\.\d{1,2})?)(?=$|\s|[-–—,:])/g;let m;while((m=rx.exec(raw))){const token=m[2],n=Number(token.replace(/,/g,''));if(!Number.isFinite(n)||n<5||(n>=1900&&n<=2100))continue;const start=m.index+m[1].length,end=start+token.length,before=raw.slice(Math.max(0,start-3),start),after=raw.slice(end,end+4);if(/[A-Za-z]$/.test(before)||/^[A-Za-z]/.test(after))continue;candidates.push({n,start,end})}return candidates.length?candidates[candidates.length-1]:null}
  function parseItem(line){let raw=cleanLine(line);if(!raw)return null;raw=raw.replace(/^[-–—]+\s*/,'').trim();let price=null,body=raw,priced=false;const hit=findLikelyPrice(raw);if(hit){price=hit.n;body=(raw.slice(0,hit.start)+' '+raw.slice(hit.end)).replace(/\s+/g,' ').trim();priced=true}body=body.replace(/\s*[-–—:=]\s*$/,'').replace(/^\s*[-–—:=]\s*/,'').trim();let{q,desc}=parseQtyAndDesc(body);if(!desc||desc.length<2)return null;if(NO_QTY_CONTEXT.test(desc))q='';return{q,d:desc,p:priced?String(price):'',priced,raw}}
  function parseCollated(text){const lines=String(text||'').split(/\r?\n/).map(cleanLine).filter(Boolean),{fields,consumed}=extractTopFields(lines),items=[];let pricedSeen=false;lines.forEach((line,i)=>{if(consumed.has(i))return;if(/^(subtotal|grand total|total|gst|tax|discount|quotation|quote|invoice)\b/i.test(line))return;const x=parseItem(line);if(!x)return;if(x.priced)pricedSeen=true;if(!pricedSeen&&!x.priced)return;if(!x.priced&&!document.getElementById('collatedIncluded')?.checked)return;x.included=!x.priced;items.push(x)});return{fields,groups:items.length?[{title:'REPAIR',items}]:[],count:items.length}}
  function prefill(fields){const map={customer:'customer',phone:'phone',vehicle:'vehicle',model:'model',mileage:'mileage'};Object.entries(map).forEach(([k,id])=>{const e=document.getElementById(id);if(e&&!e.value&&fields[k])e.value=k==='vehicle'?fields[k].replace(/\s/g,'').toUpperCase():fields[k]})}
  function preview(){const text=document.getElementById('collatedText')?.value||'',out=document.getElementById('collatedPreview');if(!out)return null;if(!text.trim()){out.innerHTML='<span class="small">Paste a list above to preview it.</span>';return null}const r=parseCollated(text);if(!r.count){out.innerHTML='<span class="small">No priced quotation items detected.</span>';return r}const g=r.groups[0];out.innerHTML=`<div style="font-size:11px;font-weight:700;margin-bottom:6px">${r.count} item${r.count===1?'':'s'} detected — will be imported as 1 repair section</div><div style="margin:6px 0">${g.items.map(x=>`<div style="display:grid;grid-template-columns:62px 1fr 72px;gap:6px;font-size:10.5px;padding:3px 0;border-bottom:1px solid #eef1f4"><span>${escHtml(x.q)}</span><span>${escHtml(x.d)}${x.included?' <em>(Included)</em>':''}</span><span style="text-align:right">${x.included?'':('$'+Number(x.p).toFixed(2))}</span></div>`).join('')}</div>`;return r}
  function fillQuote(){const r=preview();if(!r||!r.count)return;prefill(r.fields);const g=r.groups[0],imported=section({title:'REPAIR',items:g.items.map(x=>item({q:x.q,d:x.d,p:x.p,included:x.included}))});const mode=document.getElementById('collatedMode')?.value||'replace';if(mode==='append')S.push(imported);else S.splice(0,S.length,imported);render();upd();const status=document.getElementById('collatedStatus');if(status)status.textContent=`Added ${r.count} item${r.count===1?'':'s'} as one REPAIR section. You can split or rename sections manually afterwards.`;document.querySelector('.sections-panel')?.scrollIntoView({behavior:'smooth',block:'start'})}
  function panelHtml(){return '<div class="panel-title" style="color:#1d4ed8">PASTE / IMPORT COLLATED LIST</div><textarea id="collatedText" rows="9" placeholder="Paste repair list here" style="display:block;width:100%;min-height:190px;box-sizing:border-box;resize:vertical;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;color:#111827"></textarea><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px"><div><label>Import Mode</label><select id="collatedMode"><option value="replace">Replace current items</option><option value="append">Add to current quotation</option></select></div><label style="display:flex;align-items:flex-end;gap:7px;padding-bottom:9px"><input id="collatedIncluded" type="checkbox" checked style="width:16px"> Unpriced lines after first value = Included</label></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px"><button id="collatedPreviewBtn" class="btn secondary" type="button">Preview Breakdown</button><button id="collatedFillBtn" class="btn primary" type="button">Fill as 1 Repair</button></div><div id="collatedPreview" style="margin-top:9px;padding:9px;border:1px solid #e2e8f0;border-radius:8px;background:#f8fafc"><span class="small">Paste a list above to preview it.</span></div><div id="collatedStatus" class="small" style="margin-top:7px"></div>'}
  function ensurePanel(){document.querySelectorAll('.scan-panel').forEach(el=>el.remove());const settings=document.querySelector('.settings-panel');if(!settings)return;let panel=document.getElementById('collatedPanel');if(!panel){panel=document.createElement('div');panel.id='collatedPanel';panel.className='panel';panel.style.borderLeft='4px solid #2563eb';settings.parentNode.insertBefore(panel,settings)}if(!document.getElementById('collatedText')||!document.getElementById('collatedPreviewBtn')||!document.getElementById('collatedFillBtn'))panel.innerHTML=panelHtml();const p=document.getElementById('collatedPreviewBtn'),f=document.getElementById('collatedFillBtn');if(p)p.onclick=preview;if(f)f.onclick=fillQuote}
  function install(){ensurePanel();setTimeout(ensurePanel,300);setTimeout(ensurePanel,1200);new MutationObserver(()=>ensurePanel()).observe(document.querySelector('.editor')||document.body,{childList:true,subtree:true})}
  window.auaPreviewCollatedList=preview;window.auaFillCollatedList=fillQuote;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,50));else setTimeout(install,50);
})();