// Alan's United Auto - Text -> Quotation importer (restored v53)
// Paste workshop parts lists and convert them into one quotation section.
// Quantity defaults to 1 unless an explicit multiplier such as x2 is present.
(function(){
  const NO_QTY_CONTEXT=/labou?r|workmanship|diagnos|inspection fee|outside service|program|coding|calibrat|road test|service charge/i;
  function escHtml(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
  function cleanLine(s){return String(s||'').replace(/[•·]/g,' ').replace(/\t/g,' ').replace(/\s+/g,' ').trim()}
  function extractTopFields(lines){const fields={},patterns={customer:/^(?:customer(?:\s*name)?|name)\s*[:\-]\s*(.+)$/i,phone:/^(?:phone|mobile|contact|tel)\s*[:\-]\s*(.+)$/i,vehicle:/^(?:vehicle(?:\s*(?:no|number))?|car\s*(?:no|number)|registration|reg\s*no)\s*[:\-]\s*(.+)$/i,model:/^(?:model|vehicle\s*model|car\s*model)\s*[:\-]\s*(.+)$/i,mileage:/^(?:mileage|odo|odometer)\s*[:\-]\s*(.+)$/i};const consumed=new Set();lines.forEach((line,i)=>{for(const[k,rx]of Object.entries(patterns)){const m=line.match(rx);if(m){fields[k]=m[1].trim();consumed.add(i);break}}});return{fields,consumed}}

  const PRICE_RX=/(?:S\$|SGD|\$)\s*([0-9][0-9,]*(?:\.\d{1,2})?)/ig;
  const NA_RX=/\b(?:N\.?\s*\/?\s*A\.?|NOT\s+AVAILABLE)\b/i;
  const SOURCE_RX=/\b(?:ORI(?:GINAL)?|OEM|SEG)\b/ig;
  function stripListNumber(v){return cleanLine(v).replace(/^\s*\d{1,3}\s*[.)\-:]?\s+/,'').trim()}
  function amount(v){const n=Number(String(v||'').replace(/,/g,''));return Number.isFinite(n)?n:null}
  function money2(n){return Number(n||0).toLocaleString('en-SG',{minimumFractionDigits:2,maximumFractionDigits:2})}
  function tidy(v){return cleanLine(v).replace(/\s+([,;:)])/g,'$1').replace(/([(])\s+/g,'$1').replace(/\s*[-–—:=]\s*$/,'').replace(/^\s*[-–—:=]\s*/,'').trim().toUpperCase()}
  function stripSourceWords(v){return String(v||'').replace(SOURCE_RX,' ').replace(/\s+\bOR\b\s*$/i,' ').replace(/\s+/g,' ').trim()}
  function cleanDescription(v){return tidy(stripSourceWords(v))}
  function leadingQty(v){const m=v.match(/^\s*([0-9]+(?:\.\d+)?)\s*(?:PCS?|PIECES?|SETS?|UNITS?|PAIRS?|BOTTLES?|LITRES?|LITERS?|LTRS?)\b\s*/i);return m?{q:m[1],body:v.slice(m[0].length).trim()}:null}
  function prices(raw){const rx=new RegExp(PRICE_RX.source,'ig'),out=[];let m;while((m=rx.exec(raw))){const n=amount(m[1]);if(n!==null)out.push({n,start:m.index,end:m.index+m[0].length})}return out}
  function firstPrice(raw){const p=prices(raw)[0];if(!p)return null;const tail=raw.slice(p.end),m=tail.match(/^\s*x\s*([0-9]+(?:\.\d+)?)/i);return{...p,mult:m?Number(m[1]):1}}
  function additiveTerms(raw,first){if(!first)return[];const out=[{n:first.n,mult:first.mult||1}],tail=raw.slice(first.end),rx=/\+\s*(?:(?:S\$|SGD|\$)\s*)?([0-9][0-9,]*(?:\.\d{1,2})?)(?:\s*x\s*([0-9]+(?:\.\d+)?))?/ig;let m;while((m=rx.exec(tail))){const n=amount(m[1]),mult=m[2]?Number(m[2]):1;if(n!==null&&Number.isFinite(mult)&&mult>0)out.push({n,mult})}return out}
  function alternativeDescription(raw,ps){return cleanDescription(raw.slice(0,ps[0].start))}
  function parseItem(line){
    let raw=stripListNumber(line);if(!raw)return null;
    if(/^(?:SUBTOTAL|GRAND\s+TOTAL|TOTAL|GST|TAX|DISCOUNT|QUOTATION|QUOTE|INVOICE)\b/i.test(raw))return null;
    let q='1';const lead=leadingQty(raw);if(lead){q=lead.q;raw=lead.body}
    const ps=prices(raw),first=firstPrice(raw),hasNA=NA_RX.test(raw);
    if(!first){const d=cleanDescription(raw);return d&&d.length>1?{q,d,p:'',priced:false,kind:hasNA?'na':'unpriced',raw}:null}
    const plus=additiveTerms(raw,first);
    if(plus.length>1){const total=plus.reduce((s,t)=>s+t.n*t.mult,0),d=cleanDescription(raw.slice(0,first.start));return{q:'1',d:d||cleanDescription(raw),p:String(Number(total.toFixed(2))),priced:true,kind:'combined',raw}}
    if(ps.length>1)return{q:'1',d:alternativeDescription(raw,ps),p:'',priced:false,kind:'alternative',raw};
    let after=raw.slice(first.end);const xm=after.match(/^\s*x\s*([0-9]+(?:\.\d+)?)/i);if(xm){const n=Number(xm[1]);if(Number.isFinite(n)&&n>0)q=String(n);after=after.slice(xm[0].length)}
    const d=cleanDescription(raw.slice(0,first.start)+' '+after);return d?{q,d,p:String(first.n),priced:true,kind:'priced',raw}:null
  }
  function parseCollated(value){
    const lines=String(value||'').split(/\r?\n/).map(cleanLine).filter(Boolean),{fields,consumed}=extractTopFields(lines),items=[];
    lines.forEach((line,i)=>{if(consumed.has(i))return;const x=parseItem(line);if(x)items.push(x)});
    return{fields,groups:items.length?[{title:'REPAIR / PARTS',items}]:[],count:items.length,review:items.filter(x=>!x.p).length}
  }
  function prefill(fields){const map={customer:'customer',phone:'phone',vehicle:'vehicle',model:'model',mileage:'mileage'};Object.entries(map).forEach(([k,id])=>{const e=document.getElementById(id);if(e&&!e.value&&fields[k])e.value=k==='vehicle'?fields[k].replace(/\s/g,'').toUpperCase():fields[k]})}
  function preview(){const source=document.getElementById('collatedText'),out=document.getElementById('collatedPreview');if(!source||!out)return null;const raw=source.value||'';if(!raw.trim()){out.innerHTML='<span class="small">Paste a parts or repair list above to preview it.</span>';return null}const r=parseCollated(raw);if(!r.count){out.innerHTML='<span class="small">No quotation lines detected.</span>';return r}const g=r.groups[0];out.innerHTML='<div style="display:flex;justify-content:space-between;gap:10px;font-size:10.5px;font-weight:700;margin-bottom:6px"><span>'+r.count+' item'+(r.count===1?'':'s')+' detected</span><span>'+(r.review?r.review+' price'+(r.review===1?'':'s')+' to review':'Ready to import')+'</span></div><div>'+g.items.map((x,i)=>'<div style="display:grid;grid-template-columns:24px 42px 1fr 78px;gap:6px;font-size:10.5px;padding:4px 0;border-bottom:1px solid #eef1f4"><span>'+(i+1)+'</span><span>'+escHtml(x.q||'1')+'</span><span>'+escHtml(x.d)+(x.kind==='alternative'?'<br><em style="color:#9a5a08;font-size:8.5px">CHECK ALTERNATIVE PRICE</em>':x.kind==='combined'?'<br><em style="color:#52677f;font-size:8.5px">COMBINED PRICE</em>':'')+'</span><span style="text-align:right;font-weight:700">'+(x.p!==''?'S$ '+money2(x.p):'—')+'</span></div>').join('')+'</div>';return r}
  function fillQuote(){const r=preview();if(!r||!r.count)return;if(typeof S==='undefined'||typeof section!=='function'||typeof item!=='function'||typeof render!=='function'||typeof upd!=='function'){alert('Quotation editor is still loading. Please try again in a moment.');return}prefill(r.fields);const g=r.groups[0],imported=section({title:'REPAIR / PARTS',items:g.items.map(x=>item({q:x.q||'1',d:x.d,p:x.p,included:false}))}),mode=document.getElementById('collatedMode')?.value||'replace';if(mode==='append')S.push(imported);else S.splice(0,S.length,imported);render();upd();const status=document.getElementById('collatedStatus');if(status)status.textContent='Added '+r.count+' item'+(r.count===1?'':'s')+' to the quotation.'+(r.review?' '+r.review+' price'+(r.review===1?'':'s')+' left blank for review.':'');document.querySelector('.sections-panel')?.scrollIntoView({behavior:'smooth',block:'start'})}
  function install(){const sections=document.querySelector('.sections-panel');if(!sections||document.getElementById('collatedPanel'))return;const panel=document.createElement('div');panel.id='collatedPanel';panel.className='panel';panel.style.borderColor='#d7e4f3';panel.innerHTML='<div class="panel-title" style="color:#1d4ed8">TEXT → QUOTATION</div><textarea id="collatedText" rows="9" placeholder="Paste parts / repair list here" style="display:block;width:100%;min-height:180px;box-sizing:border-box;resize:vertical;padding:10px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;color:#111827;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;line-height:1.45;text-transform:none!important"></textarea><div style="display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:end;margin-top:8px"><div><label>Import Mode</label><select id="collatedMode"><option value="replace">Replace current items</option><option value="append">Add as new section</option></select></div><button id="collatedPreviewBtn" class="btn secondary" type="button">Preview</button><button id="collatedFillBtn" class="btn primary" type="button">Fill Quotation</button></div><div class="small" style="margin-top:7px;line-height:1.45">Quantity defaults to 1 unless an explicit multiplier such as x2 is detected. Additive prices are totalled. Source words such as ORI / OEM / SEG are removed. Lines with multiple alternative prices are left blank for review.</div><div id="collatedPreview" style="margin-top:9px;padding:9px;border:1px solid #e2e8f0;border-radius:8px;background:#f8fafc;max-height:300px;overflow:auto"><span class="small">Paste a parts or repair list above to preview it.</span></div><div id="collatedStatus" class="small" style="margin-top:7px;color:#315a85;font-weight:700"></div>';sections.parentNode.insertBefore(panel,sections);document.getElementById('collatedPreviewBtn').onclick=preview;document.getElementById('collatedFillBtn').onclick=fillQuote}
  window.AUATextQuotationV54={parseText:parseCollated,parseItem,preview,fillQuote};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,50));else setTimeout(install,50);
})();