// Alan's United Auto - optimized direct editing from quotation preview.
(function(){
 const $=id=>document.getElementById(id),undo=[],clone=o=>JSON.parse(JSON.stringify(o));let queued=false;
 function sections(){try{return typeof S!=='undefined'&&Array.isArray(S)?S:null}catch{return null}}
 function snap(){const ss=sections();return {fields:['customer','phone','vehicle','mileage','model','date','remarks','overallType','overallDisc'].reduce((o,id)=>(o[id]=$(id)?.value||'',o),{}),sections:ss?clone(ss):[]}}
 function pushUndo(){undo.push(snap());if(undo.length>40)undo.shift()}
 function refresh(){try{render()}catch(e){}try{upd()}catch(e){}}
 function restore(s){if(!s)return;Object.entries(s.fields||{}).forEach(([id,v])=>{if($(id))$(id).value=v});const ss=sections();if(ss)ss.splice(0,ss.length,...clone(s.sections||[]));refresh()}
 window.auaPushUndo=pushUndo;window.auaUndoRight=()=>{const s=undo.pop();if(!s)return false;restore(s);return true};
 function style(){if($('auaPreviewEditStyles'))return;const s=document.createElement('style');s.id='auaPreviewEditStyles';s.textContent=`.paper .aua-editable{cursor:text;border-radius:3px;min-height:1em}.paper .aua-editable:hover{background:#eff6ff;outline:1px dashed #60a5fa}.paper .aua-editing{background:#fff!important;outline:2px solid #2563eb!important;padding:1px 3px;min-width:28px!important;display:inline-block!important}.paper .meta span.aua-editable{display:inline-block;min-width:52px;min-height:14px}.paper .line>div.aua-editable{min-height:16px;padding:0 2px}.paper .sectitle.aua-editable{display:inline-block;min-width:55px;padding:1px 3px}.paper .summary,.paper .totals,.paper .line>div:nth-child(4){cursor:default}.paper .aua-empty-phone{display:inline!important}@media print{.paper .aua-editable:hover,.paper .aua-editing{background:transparent!important;outline:none!important;padding:0}.paper .aua-empty-phone{display:none!important}}`;document.head.appendChild(s)}
 function commit(el,get,set,opts={}){if(!el||el.dataset.auaEditing==='1')return;el.dataset.auaEditing='1';el.classList.add('aua-editing');el.contentEditable='true';const original=String(get()??'');el.textContent=original;el.focus();const r=document.createRange();r.selectNodeContents(el);r.collapse(false);const sel=getSelection();sel.removeAllRanges();sel.addRange(r);let done=false;function finish(cancel){if(done)return;done=true;el.contentEditable='false';el.classList.remove('aua-editing');delete el.dataset.auaEditing;if(!cancel){let v=el.textContent.trim();if(opts.upper)v=v.toUpperCase();if(opts.number)v=v.replace(/[^0-9.]/g,'');if(v!==original){pushUndo();set(v)}}queueMark()}el.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();finish(false)}else if(e.key==='Escape'){e.preventDefault();el.textContent=original;finish(true)}};el.onblur=()=>finish(false)}
 function bind(el,handler,title='Click to edit'){if(!el)return;el.classList.add('aua-editable');el.title=title;if(el.dataset.auaEditBound==='1')return;el.dataset.auaEditBound='1';el.onclick=e=>{e.preventDefault();e.stopPropagation();handler(el)}}
 function mark(){const ss=sections();if(!ss)return;const phone=$('phone'),wrap=$('pphoneWrap');if(wrap&&phone&&!phone.value.trim()){wrap.classList.add('aua-empty-phone');wrap.style.display='inline'}const map={pc:'customer',pphone:'phone',pv:'vehicle',pm:'mileage',pmod:'model'};Object.entries(map).forEach(([pid,iid])=>{const p=$(pid),input=$(iid);if(p&&input)bind(p,el=>commit(el,()=>input.value,v=>{input.value=v;upd()},{upper:!['phone','mileage'].includes(iid)}))});const pd=$('pd'),date=$('date');if(pd&&date)bind(pd,el=>commit(el,()=>date.value,v=>{date.value=v;upd()}));const remarks=$('pRemarks'),rin=$('remarks');if(remarks&&rin){if(!rin.value){remarks.style.display='block';remarks.style.minHeight='18px'}bind(remarks,el=>commit(el,()=>rin.value,v=>{rin.value=v;upd()},{upper:true}))}document.querySelectorAll('#psecs .secprint').forEach((card,si)=>{const sec=ss[si];if(!sec)return;bind(card.querySelector('.sectitle'),el=>commit(el,()=>sec.title||'',v=>{sec.title=v.toUpperCase();refresh()},{upper:true}));card.querySelectorAll('.line').forEach((line,ii)=>{const item=sec.items?.[ii];if(!item)return;const c=line.children;if(c[0])bind(c[0],el=>commit(el,()=>item.q??'',v=>{item.q=v;refresh()}));if(c[1])bind(c[1],el=>commit(el,()=>item.d??'',v=>{item.d=v.toUpperCase();refresh()},{upper:true}));if(c[2])bind(c[2],el=>commit(el,()=>item.p??'',v=>{item.p=v;refresh()},{number:true}))})})}
 function queueMark(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;mark()})}
 function install(){style();queueMark();if(typeof window.upd==='function'&&!window.__auaPreviewUpdPatched){window.__auaPreviewUpdPatched=true;const old=window.upd;window.upd=function(){const r=old.apply(this,arguments);queueMark();return r}}if(typeof window.render==='function'&&!window.__auaPreviewRenderPatched){window.__auaPreviewRenderPatched=true;const old=window.render;window.render=function(){const r=old.apply(this,arguments);queueMark();return r}}document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey)||e.key.toLowerCase()!=='z'||e.shiftKey)return;const a=document.activeElement,typing=a&&(a.isContentEditable||/^(INPUT|TEXTAREA|SELECT)$/i.test(a.tagName));if(typing||!undo.length)return;e.preventDefault();e.stopImmediatePropagation();window.auaUndoRight()},true)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,650));else setTimeout(install,650);
})();